"""Stories as data for storydags.py. Every step lists exactly what it adds.

Notation (the renderer turns X_n into a subscript):
- each repository is a letter: U umbrella, T trunc, D dotsync, …; a tool
  that appears twice in a composition has occurrences R1, R2
- commits are U_1, U_2, …, with U_2a, U_2b for two lines from one point,
  and U_3′ for a new version of U_3 (same change)
- π_T(U_3): the trunc commit that umbrella commit U_3 maps down to, when
  U_3 is where it first appears (a derived commit)
- ρ_U(T_5): the umbrella commit that stands for T_5 (its rep), when it was
  brought in from outside; ρ_U.R2(R_5) is the rep at occurrence R2

Placement rule under test (C″): a brought-in rep is built on the reps of
its tool parents; for tool merges, the tree outside the tool path is Git's
merge of the parents' reps' trees. A tool commit derived from umbrella
commit u has u as its rep (W14). Bringing in is two explicit steps: create
the rep (deterministic, like a fetch), then an ordinary merge.
"""

T = ("T", "trunc")
D = ("D", "dotsync")
U = ("U", "umbrella")


S5_START = [
    {
        "title": "Start",
        "commits": [("T", "T_4"), ("U", "U_2")],
        "rep": [("U_2", "T_4")],
    },
    {
        "title": "Ada commits the red (test) change in the umbrella",
        "cmds": ["ada$ git commit -m 'Add failing test for --config'   → U_3 (changes tools/trunc/tests/)"],
        "commits": [("U", "U_3", "red"), ("T", "π_T(U_3)")],
        "edges": [("U_2", "U_3"), ("T_4", "π_T(U_3)")],
        "made": [("U_3", "π_T(U_3)")],
        "text": "Mapping U_3 down gives a new trunc commit, π_T(U_3), with parent T_4. U_3 is where it was made, so U_3 is its rep. Publishing copies π_T(U_3) to trunc; the DAG doesn't change.",
    },
    {
        "title": "ratchet-bot commits T_5 on π_T(U_3) in trunc",
        "cmds": ["ada$ gh workflow run ledger.yml --ref main -f target=13", "bot$ commit .test-status.json: pending   → T_5, parent π_T(U_3)"],
        "commits": [("T", "T_5", "bot")],
        "edges": [("π_T(U_3)", "T_5")],
    },
    {
        "title": "Ada brings T_5 in; its rep sits directly on her own commit U_3",
        "cmds": ["ada$ cx fetch trunc   → ρ_U(T_5): parent U_3 (the rep of π_T(U_3)), tree = U_3's with tools/trunc := T_5"],
        "commits": [("U", "ρ_U(T_5)")],
        "edges": [("U_3", "ρ_U(T_5)")],
        "rep": [("ρ_U(T_5)", "T_5")],
        "text": "ρ_U(T_5) descends from U_3, so Ada's line simply continues from ρ_U(T_5). No merge is needed. From now on U_3 has someone else's work on top of it: it is <em>shared</em>.",
    },
]


def s7_steps(merge):
    """S7's steps, with Max's joining merge named `merge` (S7a numbers it later)."""
    return [
        {
            "title": "Start: the umbrella has reps of B_1, B_2, B_3, and more work on top (U_1)",
            "commits": [("B", "B_1"), ("B", "B_2", "bad ledger"), ("B", "B_3"), ("U", "ρ_U(B_1)"), ("U", "ρ_U(B_2)"), ("U", "ρ_U(B_3)"), ("U", "U_1")],
            "edges": [("B_1", "B_2"), ("B_2", "B_3"), ("ρ_U(B_1)", "ρ_U(B_2)"), ("ρ_U(B_2)", "ρ_U(B_3)"), ("ρ_U(B_3)", "U_1")],
            "rep": [("ρ_U(B_1)", "B_1"), ("ρ_U(B_2)", "B_2"), ("ρ_U(B_3)", "B_3")],
            "is": [("U_1", "B_3")],
            "text": "U_1 changes only the umbrella's README, so it <em>is</em> B_3.",
        },
        {
            "title": "tb is rewritten: B_2′, B_3′ replace B_2, B_3",
            "cmds": ["max$ (in tb) rebuild from B_2 with repaired ledgers   → B_2′, B_3′", "max$ git tag backup/tb-main-2026-09-09 B_3 && git push --force origin main"],
            "commits": [("B", "B_2′"), ("B", "B_3′")],
            "edges": [("B_1", "B_2′"), ("B_2′", "B_3′")],
            "dim": ["B_2", "B_3"],
            "text": "B_2 and B_3 still exist (the backup tag holds them), but no one's work continues from them. The umbrella's ρ_U(B_2), ρ_U(B_3) and U_1 are untouched: checking out U_1 still works offline, because its tree has the files (Q-S7a).",
        },
        {
            "title": "Max creates reps for the new history, built on B_1's rep",
            "cmds": ["max$ cx fetch tb   → ρ_U(B_2′) on ρ_U(B_1), ρ_U(B_3′) on ρ_U(B_2′)", "tb: B_3′ replaces B_3 (tb's main moved from B_3 to B_3′ without containing it)"],
            "commits": [("U", "ρ_U(B_2′)"), ("U", "ρ_U(B_3′)")],
            "edges": [("ρ_U(B_1)", "ρ_U(B_2′)"), ("ρ_U(B_2′)", "ρ_U(B_3′)")],
            "rep": [("ρ_U(B_2′)", "B_2′"), ("ρ_U(B_3′)", "B_3′")],
            "text": "\"B_3′ replaces B_3\" comes from how tb's label moved, which is level-2 information. At level 1, CloneX takes it as an input (or Max states it).",
        },
        {
            "title": f"Max merges it, with B_3 as the base for tools/tb → {merge}",
            "cmds": [f"max$ cx merge tb   → {merge}, recording that B_3′ replaces B_3"],
            "commits": [("U", merge)],
            "edges": [("U_1", merge), ("ρ_U(B_3′)", merge)],
            "is": [(merge, "B_3′")],
            "hazard": "A plain <code>git merge</code> uses ρ_U(B_1) as the base. Both sides changed the ledger since B_1, differently, so it conflicts in <code>.test-status.json</code>, a file the umbrella never touched. And mapping the merge down without the replacement record gives a new tb commit merging B_3 and B_3′, which would put the bad history back into tb if anyone published it.",
            "verdict": f"CloneX's merge uses the replaced commit B_3 as the base for tools/tb. The umbrella's side is exactly B_3, so tools/tb simply becomes B_3′, with no conflict (Q-S7b). {merge} records, in the commit itself, that B_3′ replaces B_3, so every machine maps it down the same way: {merge} <em>is</em> B_3′ (Q-S2e). The record names commits, not labels (D1). How it is written is parked.",
        },
    ]


STORIES = [
    {
        "id": "S2b",
        "title": "Half-landed cross-tool change",
        "repos": [T, U, D],
        "compositions": ["U"],
        "setup": "Max makes one umbrella commit U_4 that changes trunc and dotsync. trunc merges its part first; dotsync later.",
        "steps": [
            {
                "title": "Start: the umbrella contains trunc at T_4 and dotsync at D_2",
                "commits": [("T", "T_4"), ("U", "U_3"), ("D", "D_2")],
                "is": [("U_3", "T_4"), ("U_3", "D_2")],
                "text": "The reps of T_4 and D_2 are earlier umbrella commits, not shown.",
            },
            {
                "title": "Max commits U_4; it is the rep of two tool commits",
                "cmds": ["max$ git commit -am 'Alias AGENTS.md as CLAUDE.md everywhere'   → U_4"],
                "commits": [("U", "U_4"), ("T", "π_T(U_4)"), ("D", "π_D(U_4)")],
                "edges": [("U_3", "U_4"), ("T_4", "π_T(U_4)"), ("D_2", "π_D(U_4)")],
                "made": [("U_4", "π_T(U_4)"), ("U_4", "π_D(U_4)")],
                "text": "Mapping U_4 down gives π_T(U_4) (parent T_4) and π_D(U_4) (parent D_2). They were made from U_4, so U_4 is their rep (W14).",
            },
            {
                "title": "trunc merges its part (T_5); its rep ρ_U(T_5) is created",
                "cmds": ["github$ merge trunc PR #13  → T_5 = merge(T_4, π_T(U_4))", "max$ cx fetch trunc          → creates ρ_U(T_5)"],
                "commits": [("T", "T_5"), ("U", "ρ_U(T_5)")],
                "edges": [("T_4", "T_5"), ("π_T(U_4)", "T_5"), ("U_3", "ρ_U(T_5)"), ("U_4", "ρ_U(T_5)")],
                "rep": [("ρ_U(T_5)", "T_5")],
                "is": [("ρ_U(T_5)", "π_D(U_4)")],
                "verdict": "ρ_U(T_5)'s parents are the reps of T_5's parents: U_3 (for T_4) and U_4 (for π_T(U_4)). Its tree outside trunc is Git's merge of U_3 and U_4, which is U_4's. So it contains all of U_4. That's consistent: it <em>is</em> π_D(U_4) in dotsync. Whether a label should point here is level 2.",
            },
            {
                "title": "Jim's T_6 lands on trunc; its rep is built on T_5's rep",
                "cmds": ["github$ merge trunc PR #14  → T_6 (Jim), parent T_5", "max$ cx fetch trunc          → creates ρ_U(T_6) on ρ_U(T_5)"],
                "commits": [("T", "T_6", "Jim"), ("U", "ρ_U(T_6)")],
                "edges": [("T_5", "T_6"), ("ρ_U(T_5)", "ρ_U(T_6)")],
                "rep": [("ρ_U(T_6)", "T_6")],
                "is": [("ρ_U(T_6)", "π_D(U_4)")],
            },
            {
                "title": "dotsync merges its part (D_3); the umbrella now has two divergent lines",
                "cmds": ["github$ merge dotsync PR #51 → D_3 = merge(D_2, π_D(U_4))", "max$ cx fetch dotsync        → creates ρ_U(D_3)"],
                "commits": [("D", "D_3"), ("U", "ρ_U(D_3)")],
                "edges": [("D_2", "D_3"), ("π_D(U_4)", "D_3"), ("U_3", "ρ_U(D_3)"), ("U_4", "ρ_U(D_3)")],
                "rep": [("ρ_U(D_3)", "D_3")],
                "is": [("ρ_U(D_3)", "π_T(U_4)")],
                "verdict": "Nothing joins ρ_U(T_6) and ρ_U(D_3) yet. No umbrella commit contains both tools' latest. That's normal divergence, and every commit is still one real commit of each tool.",
            },
            {
                "title": "Someone explicitly merges the two lines in the umbrella",
                "cmds": ["max$ git merge ρ_U(D_3)   (while on ρ_U(T_6)'s line) → U_5"],
                "commits": [("U", "U_5")],
                "edges": [("ρ_U(T_6)", "U_5"), ("ρ_U(D_3)", "U_5")],
                "is": [("U_5", "T_6"), ("U_5", "D_3")],
                "verdict": "Clean: the shared ancestor is U_4, and each side changed a different tool since then.",
            },
        ],
        "conclusion": "every tool commit gets exactly one rep; a rep's parents are its tool parents' reps; the umbrella never follows a tool implicitly. Its commits join by explicit merges.",
    },
    {
        "id": "S10",
        "title": "Ada and Max bring in the same commit",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "Ada and Max each have their own umbrella commit on U_2 (Ada edits README, Max edits crates/). Jim's typo fix T_5 lands on trunc. Each of them brings it in on their own machine.",
        "steps": [
            {
                "title": "Start",
                "commits": [("T", "T_4"), ("U", "U_2"), ("U", "U_3a", "Ada"), ("U", "U_3b", "Max")],
                "edges": [("U_2", "U_3a"), ("U_2", "U_3b")],
                "rep": [("U_2", "T_4")],
                "is": [("U_3a", "T_4"), ("U_3b", "T_4")],
                "text": "U_2 is the rep of T_4. U_3a and U_3b don't touch trunc, so both <em>are</em> T_4 too, but neither is its rep.",
            },
            {
                "title": "Jim's fix T_5 lands on trunc",
                "commits": [("T", "T_5", "Jim")],
                "edges": [("T_4", "T_5")],
            },
            {
                "title": "Ada's machine creates T_5's rep",
                "cmds": ["ada$ cx fetch trunc   → ρ_U(T_5): parent U_2 (rep of T_4), tree = U_2's tree with tools/trunc := T_5"],
                "commits": [("U", "ρ_U(T_5)")],
                "edges": [("U_2", "ρ_U(T_5)")],
                "rep": [("ρ_U(T_5)", "T_5")],
            },
            {
                "title": "Ada merges it explicitly",
                "cmds": ["ada$ git merge ρ_U(T_5)   → U_4a"],
                "commits": [("U", "U_4a")],
                "edges": [("U_3a", "U_4a"), ("ρ_U(T_5)", "U_4a")],
                "is": [("U_4a", "T_5")],
            },
            {
                "title": "Max's machine creates T_5's rep: the identical object, so no new commit",
                "cmds": ["max$ cx fetch trunc   → ρ_U(T_5) again: same parent, tree, author, message → same SHA"],
                "text": "The DAG doesn't change. Max's copy of ρ_U(T_5) is byte-for-byte Ada's, because every input to it (T_5, U_2) is shared.",
            },
            {
                "title": "Max merges it explicitly",
                "cmds": ["max$ git merge ρ_U(T_5)   → U_4b"],
                "commits": [("U", "U_4b")],
                "edges": [("U_3b", "U_4b"), ("ρ_U(T_5)", "U_4b")],
                "is": [("U_4b", "T_5")],
            },
            {
                "title": "Their lines are merged",
                "cmds": ["max$ git merge U_4a   → U_5"],
                "commits": [("U", "U_5")],
                "edges": [("U_4b", "U_5"), ("U_4a", "U_5")],
                "is": [("U_5", "T_5")],
                "verdict": "The shared ancestor includes ρ_U(T_5), so Jim's fix is one commit in the umbrella's history. A later trunc revert of T_5 merges correctly (the duplicate hazard can't arise).",
            },
        ],
        "conclusion": "a rep is a function of the tool commit and its parents' reps only, so every machine creates the same one. Bringing in is create-rep, then explicit merge.",
    },
    {
        "id": "S11",
        "title": "Ada rebases with plain Git",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "Continuing S10 before Max merges. Ada's line is U_3a (her README change) and U_4a, her merge of ρ_U(T_5). Max's line is U_3b. Ada wants her work on top of Max's, and runs plain <code>git rebase U_3b</code>. Each step below is one thing Git does; it was checked against a real repository with this history (git 2.55).",
        "steps": [
            {
                "title": "Start",
                "commits": [("T", "T_4"), ("T", "T_5", "Jim"), ("U", "U_2"), ("U", "U_3a", "Ada"), ("U", "U_3b", "Max"), ("U", "ρ_U(T_5)"), ("U", "U_4a", "Ada's merge")],
                "edges": [("T_4", "T_5"), ("U_2", "U_3a"), ("U_2", "U_3b"), ("U_2", "ρ_U(T_5)"), ("U_3a", "U_4a"), ("ρ_U(T_5)", "U_4a")],
                "rep": [("U_2", "T_4"), ("ρ_U(T_5)", "T_5")],
                "is": [("U_3a", "T_4"), ("U_3b", "T_4"), ("U_4a", "T_5")],
            },
            {
                "title": "Git lists the commits to move, and drops the merge",
                "cmds": ["ada$ git rebase U_3b      (Ada is on U_4a)", "", "the list Git builds (what `git rebase -i` would show):", "pick U_3a         Update README", "pick ρ_U(T_5)     Fix typo in help text"],
                "colours": {"picked": ["U_3a", "ρ_U(T_5)"], "dropped": ["U_4a"], "kept": ["U_2", "U_3b"]},
                "text": "Git takes every commit reachable from Ada's U_4a that is not reachable from U_3b: U_3a, ρ_U(T_5) and U_4a. U_2 is in both histories, so it stays. By default Git skips merge commits, so U_4a is dropped. The two that are left are put in a single line, U_3a first. Nothing is written yet; the DAG is unchanged.",
            },
            {
                "title": "Git copies U_3a onto U_3b",
                "cmds": ["Rebasing (1/2)   → U_3a′"],
                "commits": [("U", "U_3a′", "Ada, copied")],
                "edges": [("U_3b", "U_3a′")],
                "is": [("U_3a′", "T_4")],
                "colours": {"copy": ["U_3a′"], "picked": ["ρ_U(T_5)"]},
                "text": "U_3a′ makes the same change as U_3a, with the same message and author, but on a new parent, so it is a new commit with a new SHA. This is the move Ada wanted.",
            },
            {
                "title": "Git copies ρ_U(T_5) onto U_3a′",
                "cmds": ["Rebasing (2/2)   → ρ_U(T_5)′", "Successfully rebased and updated refs/heads/ada."],
                "commits": [("U", "ρ_U(T_5)′", "copy of Jim's fix")],
                "edges": [("U_3a′", "ρ_U(T_5)′")],
                "is": [("ρ_U(T_5)′", "T_5")],
                "colours": {"copy": ["ρ_U(T_5)′"]},
                "text": "ρ_U(T_5)′ keeps Jim as author and keeps the message, but its committer is now Ada, and its parent is U_3a′. It still changes tools/trunc to T_5's content, so it <em>is</em> T_5. But it is not T_5's rep: that is still ρ_U(T_5), which nothing has changed.",
            },
            {
                "title": "Ada's line now ends at the copy; the originals are left behind",
                "dim": ["U_3a", "U_4a"],
                "colours": {"copy": ["U_3a′", "ρ_U(T_5)′"], "kept": ["ρ_U(T_5)"]},
                "hazard": "The umbrella now has two commits that make Jim's change: ρ_U(T_5) (which Max will merge, as in S10) and ρ_U(T_5)′ on Ada's line. When the lines are merged, Git sees the same change made twice on two sides. That merges cleanly today, but if trunc later reverts T_5 and the revert is brought in on one side, a merge can bring Jim's change back (H2). <code>git rebase --rebase-merges</code> doesn't help: it keeps the merge, but it still copies ρ_U(T_5) (also checked).",
            },
        ],
        "conclusion": "a plain rebase copies every commit on the moved line that the target doesn't have, reps included, and drops merges. A copied rep is a duplicate. So <code>cx status</code> must detect \"a second umbrella commit for trunc T_5\", and the safe move is S11a.",
    },
    {
        "id": "S11a",
        "title": "The same move, done right",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "The same start as S11. Ada moves only her own commit U_3a onto U_3b, and keeps her merge.",
        "steps": [
            {
                "title": "Start",
                "commits": [("T", "T_4"), ("T", "T_5", "Jim"), ("U", "U_2"), ("U", "U_3a", "Ada"), ("U", "U_3b", "Max"), ("U", "ρ_U(T_5)"), ("U", "U_4a", "Ada's merge")],
                "edges": [("T_4", "T_5"), ("U_2", "U_3a"), ("U_2", "U_3b"), ("U_2", "ρ_U(T_5)"), ("U_3a", "U_4a"), ("ρ_U(T_5)", "U_4a")],
                "rep": [("U_2", "T_4"), ("ρ_U(T_5)", "T_5")],
                "is": [("U_3a", "T_4"), ("U_3b", "T_4"), ("U_4a", "T_5")],
            },
            {
                "title": "jj moves U_3a and what's built on it, and nothing else",
                "cmds": ["ada$ jj rebase -s U_3a -d U_3b", "   (plain Git: git rebase --onto U_3b U_2 U_3a, then git merge ρ_U(T_5))"],
                "commits": [("U", "U_3a′", "Ada, copied"), ("U", "U_4a′", "Ada's merge, redone")],
                "edges": [("U_3b", "U_3a′"), ("U_3a′", "U_4a′"), ("ρ_U(T_5)", "U_4a′")],
                "is": [("U_3a′", "T_4"), ("U_4a′", "T_5")],
                "dim": ["U_3a", "U_4a"],
                "colours": {"copy": ["U_3a′", "U_4a′"], "kept": ["ρ_U(T_5)"]},
                "verdict": "<code>-s U_3a</code> means \"U_3a and its descendants\": U_3a and U_4a. ρ_U(T_5) is not a descendant of U_3a, so jj doesn't touch it, and the new merge U_4a′ has the very same ρ_U(T_5) as its second parent (same SHA, checked with jj 0.44). T_5 still has exactly one umbrella commit.",
            },
        ],
        "conclusion": "move only your own commits, and keep merges of reps as merges. jj's <code>rebase -s</code> does this; plain Git needs the two-command form.",
    },
    {
        "id": "S12",
        "title": "GitHub squash-merges an umbrella PR",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "Ada's PR head is U_4a (her README change merged with ρ_U(T_5)). Nothing else in the umbrella has T_5 yet. GitHub's squash button makes one new commit U_4b on top of U_3b.",
        "steps": [
            {
                "title": "Start",
                "commits": [("T", "T_4"), ("T", "T_5", "Jim"), ("U", "U_2"), ("U", "U_3a", "Ada"), ("U", "U_3b"), ("U", "ρ_U(T_5)"), ("U", "U_4a")],
                "edges": [("T_4", "T_5"), ("U_2", "U_3a"), ("U_2", "U_3b"), ("U_2", "ρ_U(T_5)"), ("U_3a", "U_4a"), ("ρ_U(T_5)", "U_4a")],
                "rep": [("U_2", "T_4"), ("ρ_U(T_5)", "T_5")],
                "is": [("U_3a", "T_4"), ("U_3b", "T_4"), ("U_4a", "T_5")],
            },
            {
                "title": "Squash: U_4b has one parent (U_3b) and U_4a's combined changes",
                "cmds": ["github$ squash-merge Ada's PR   → U_4b (author Ada), parent U_3b"],
                "commits": [("U", "U_4b", "squash")],
                "edges": [("U_3b", "U_4b")],
                "is": [("U_4b", "T_5")],
                "dim": ["U_3a", "U_4a"],
                "hazard": "U_4b changes tools/trunc from T_4 to T_5's content, but it isn't T_5's rep. Its message carries ρ_U(T_5)'s record of which trunc commit it stands for, and the content matches, so CloneX can prove U_4b <em>is</em> T_5: publishing won't push a copy of Jim's fix authored by Ada. But the umbrella's history now has Jim's change inside U_4b, and merging U_4b's line with a line that has the real ρ_U(T_5) brings back the duplicate hazard. A merge commit instead of a squash avoids all of this.",
            },
        ],
        "conclusion": "squash merges of umbrella PRs hide reps inside a new commit. Merge-commit-only (the owner's preference) keeps every rep in the DAG. CloneX must still prove U_4b is T_5 by its record and content, so it never publishes a false copy.",
    },
    {
        "id": "S13",
        "title": "Extract crates/standards into its own repo",
        "repos": [("C", "crosscut (new)"), U],
        "compositions": ["U"],
        "setup": "The umbrella's own directory <code>crates/standards</code> becomes a new repo, crosscut (C), keeping its history. Later an outsider, Olga, contributes to crosscut directly.",
        "steps": [
            {
                "title": "Start: three umbrella commits, two of which touch crates/standards",
                "commits": [("U", "U_1"), ("U", "U_2"), ("U", "U_3")],
                "edges": [("U_1", "U_2"), ("U_2", "U_3")],
                "text": "U_1 adds standards v1; U_2 edits only the README; U_3 edits standards and the README.",
            },
            {
                "title": "Derive crosscut's history: the umbrella commits are its reps",
                "cmds": ["max$ cx extract crates/standards   → π_C(U_1), π_C(U_3)"],
                "commits": [("C", "π_C(U_1)"), ("C", "π_C(U_3)")],
                "edges": [("π_C(U_1)", "π_C(U_3)")],
                "made": [("U_1", "π_C(U_1)"), ("U_3", "π_C(U_3)")],
                "is": [("U_2", "π_C(U_1)")],
                "text": "π_C(U_1) and π_C(U_3) were made from U_1 and U_3, so those are their reps (W14). U_2 changes nothing in standards, so it <em>is</em> π_C(U_1) without being its rep. No new umbrella commits.",
            },
            {
                "title": "Meanwhile the umbrella moves on (U_4), and Olga commits C_1 to crosscut",
                "commits": [("U", "U_4"), ("C", "C_1", "Olga")],
                "edges": [("U_3", "U_4"), ("π_C(U_3)", "C_1")],
                "is": [("U_4", "π_C(U_3)")],
            },
            {
                "title": "C_1's rep is built on π_C(U_3)'s rep (U_3), a full umbrella state",
                "cmds": ["max$ cx fetch crosscut   → ρ_U(C_1): parent U_3, tree = U_3's with crates/standards := C_1"],
                "commits": [("U", "ρ_U(C_1)")],
                "edges": [("U_3", "ρ_U(C_1)")],
                "rep": [("ρ_U(C_1)", "C_1")],
            },
            {
                "title": "Explicit merge into the umbrella's current work",
                "cmds": ["max$ git merge ρ_U(C_1)   (on U_4) → U_5"],
                "commits": [("U", "U_5")],
                "edges": [("U_4", "U_5"), ("ρ_U(C_1)", "U_5")],
                "is": [("U_5", "C_1")],
                "verdict": "ρ_U(C_1) looks like an ordinary side branch from U_3 that changed only crates/standards; its merge base with U_4 is U_3, a real full state.",
            },
        ],
        "conclusion": "extraction needs no new umbrella commits: the existing ones become reps. The same placement rule covers later outside commits, and a composition-made rep has a full tree, so it's a good merge base.",
    },
    {
        "id": "S15",
        "title": "Convert a submodule umbrella",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "Today's umbrella: U_1 adds the submodule (gitlink → T_2), U_2 bumps it (gitlink → T_4). Converting must keep U_1 and U_2 untouched and give the umbrella trunc's real history.",
        "steps": [
            {
                "title": "Start: gitlinks only",
                "commits": [("T", "T_1"), ("T", "T_2"), ("T", "T_3"), ("T", "T_4"), ("U", "U_1"), ("U", "U_2")],
                "edges": [("T_1", "T_2"), ("T_2", "T_3"), ("T_3", "T_4"), ("U_1", "U_2")],
                "text": "U_1 and U_2 contain a gitlink, not files. There's no \"is\" line: a gitlink is a pointer, not content.",
            },
            {
                "title": "Create reps for trunc's history, built on the commit being converted",
                "cmds": ["max$ cx adopt tools/trunc   (on U_2) → ρ_U(T_1)…ρ_U(T_4)"],
                "commits": [("U", "ρ_U(T_1)"), ("U", "ρ_U(T_2)"), ("U", "ρ_U(T_3)"), ("U", "ρ_U(T_4)")],
                "edges": [("U_2", "ρ_U(T_1)"), ("ρ_U(T_1)", "ρ_U(T_2)"), ("ρ_U(T_2)", "ρ_U(T_3)"), ("ρ_U(T_3)", "ρ_U(T_4)")],
                "rep": [("ρ_U(T_1)", "T_1"), ("ρ_U(T_2)", "T_2"), ("ρ_U(T_3)", "T_3"), ("ρ_U(T_4)", "T_4")],
                "text": "trunc's root T_1 has no parent rep, so its rep is built on U_2, the commit being converted: U_2's tree with the gitlink replaced by T_1's files. Every rep is a full umbrella state. <code>git log -- tools/trunc</code> now shows all of trunc's commits, with their authors.",
            },
            {
                "title": "The conversion commit",
                "cmds": ["max$ git merge ρ_U(T_4) && git rm .gitmodules entry   → U_3"],
                "commits": [("U", "U_3")],
                "edges": [("ρ_U(T_4)", "U_3")],
                "is": [("U_3", "T_4")],
                "verdict": "U_1 and U_2 are unchanged (checking them out still needs the submodule, as it always did). From U_3 on, trunc's files are ordinary files. The same inputs (U_2, trunc's history) give the same reps on every machine.",
            },
        ],
        "conclusion": "history before containment gets reps built on the first containing commit, so reps always have full trees. The old umbrella history is never rewritten.",
    },
    {
        "id": "S17",
        "title": "A throwaway composition for an agent",
        "repos": [D, ("V", "view V (local only)"), ("H", "agent-harness")],
        "compositions": ["V"],
        "setup": "Ada needs dotsync and agent-harness side by side for one task, in a new composition V that exists only on her machine.",
        "steps": [
            {
                "title": "Start: two tool repos, V empty",
                "commits": [("D", "D_1"), ("D", "D_2"), ("H", "H_1")],
                "edges": [("D_1", "D_2")],
            },
            {
                "title": "Create reps for both histories",
                "cmds": ["ada$ cx new V --with dotsync --with agent-harness"],
                "commits": [("V", "ρ_V(D_1)"), ("V", "ρ_V(D_2)"), ("V", "ρ_V(H_1)")],
                "edges": [("ρ_V(D_1)", "ρ_V(D_2)")],
                "rep": [("ρ_V(D_1)", "D_1"), ("ρ_V(D_2)", "D_2"), ("ρ_V(H_1)", "H_1")],
                "hazard": "V has no earlier commit to build on, so these first reps contain only their own tool's directory. They are real V states, since V holds nothing else yet, but they are partial trees. A later merge whose base is ρ_V(D_2) sees agent-harness's files as \"added\", the narrow rename-detection residual (G1). CloneX's own merges avoid it; plain <code>git revert</code> of ρ_V(D_2) inside V would not.",
            },
            {
                "title": "V's first ordinary commit joins them",
                "cmds": ["ada$ git merge --allow-unrelated-histories   → V_1"],
                "commits": [("V", "V_1")],
                "edges": [("ρ_V(D_2)", "V_1"), ("ρ_V(H_1)", "V_1")],
                "is": [("V_1", "D_2"), ("V_1", "H_1")],
            },
            {
                "title": "Ada's change across both tools is one V commit, the rep of two tool commits",
                "cmds": ["ada$ git commit -am 'Wire harness to dotsync config'   → V_2"],
                "commits": [("V", "V_2"), ("D", "π_D(V_2)"), ("H", "π_H(V_2)")],
                "edges": [("V_1", "V_2"), ("D_2", "π_D(V_2)"), ("H_1", "π_H(V_2)")],
                "made": [("V_2", "π_D(V_2)"), ("V_2", "π_H(V_2)")],
                "verdict": "Publishing sends π_D(V_2) and π_H(V_2) to their repos. V can then be deleted. Nothing of Ada's work lives only in V once both are published.",
            },
        ],
        "conclusion": "throwaway compositions work unchanged, except that the very first reps have partial trees (a documented residual). Safe to discard V is a checkable property: no V commit is the rep of an unpublished tool commit.",
    },
    {
        "id": "S5",
        "title": "Ratchet flow: red, bot, green",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "Ada adds a test and then the implementation from the umbrella. trunc's ratchet needs red, then the bot's ledger commit, then green, in trunc's own history.",
        "steps": S5_START + [
            {
                "title": "Ada commits green on top of ρ_U(T_5)",
                "cmds": ["ada$ git commit -m 'Implement --config'   → U_4 (parent ρ_U(T_5))"],
                "commits": [("U", "U_4", "green"), ("T", "π_T(U_4)")],
                "edges": [("ρ_U(T_5)", "U_4"), ("T_5", "π_T(U_4)")],
                "made": [("U_4", "π_T(U_4)")],
                "verdict": "trunc's history is π_T(U_3) → T_5 → π_T(U_4): red, bot, green, exactly as the ratchet requires. The bot records passing next, and it arrives the same way T_5 did.",
            },
        ],
        "conclusion": "a bot commit on your published commit comes back as a rep sitting directly on your own commit, with no merge needed. The order in the tool is preserved by construction.",
    },
    {
        "id": "S5a",
        "title": "Reviewer asks for a test change: fix forward",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "After step 3 of S5, the reviewer asks for a change to the test. Ada fixes it with a new commit (append-only).",
        "steps": S5_START + [
            {
                "title": "Ada commits the test fix on top of ρ_U(T_5)",
                "cmds": ["ada$ git commit -m 'Tighten the --config test'   → U_4 (parent ρ_U(T_5))"],
                "commits": [("U", "U_4", "test fix"), ("T", "π_T(U_4)")],
                "edges": [("ρ_U(T_5)", "U_4"), ("T_5", "π_T(U_4)")],
                "made": [("U_4", "π_T(U_4)")],
                "verdict": "Nothing special. trunc gets π_T(U_3) → T_5 → π_T(U_4), the bot runs again on top, and the flow continues. This is the path that needs no machinery.",
            },
        ],
        "conclusion": "append-only fixes after outside work has built on yours need nothing new.",
    },
    {
        "id": "S5b",
        "title": "Reviewer asks for a test change: amend",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "After step 3 of S5, Ada wants to amend U_3 itself rather than add a commit.",
        "steps": S5_START + [
            {
                "title": "jj refuses: U_3 has outside work on top",
                "cmds": ["ada$ jj squash --into U_3   (with the edited test)", "Error: Commit ρ_U(T_5) is immutable  (reps are immutable heads, so U_3, its ancestor, is too)"],
                "text": "The DAG doesn't change.",
                "hazard": "Without that refusal, jj would rebase ρ_U(T_5) onto the amended U_3. The result would be a commit authored by the bot, recording a ledger for a test the bot never saw. Mapped down, it is not T_5, so publishing would push a forged bot commit into trunc. The refusal is what makes the choice explicit.",
            },
            {
                "title": "Ada explicitly drops the outside work above U_3, then amends",
                "cmds": ["ada$ cx drop-above U_3    (abandons ρ_U(T_5); CloneX lists what's dropped: trunc T_5, by ratchet-bot)", "ada$ jj squash --into U_3   → U_3′"],
                "commits": [("U", "U_3′", "red, amended"), ("T", "π_T(U_3′)")],
                "edges": [("U_2", "U_3′"), ("T_4", "π_T(U_3′)")],
                "made": [("U_3′", "π_T(U_3′)")],
                "dim": ["U_3", "ρ_U(T_5)", "π_T(U_3)", "T_5"],
                "text": "U_3′ has the same jj change-id as U_3, so CloneX knows it supersedes U_3. In trunc, π_T(U_3) and T_5 are now stale, and publishing replaces them. That is the force-update of the PR branch Ada would do today.",
            },
            {
                "title": "The bot reruns on π_T(U_3′); Ada brings it in",
                "cmds": ["ada$ cx publish && gh workflow run ledger.yml ...", "bot$ → T_6 on π_T(U_3′)", "ada$ cx fetch trunc   → ρ_U(T_6) on U_3′"],
                "commits": [("T", "T_6", "bot"), ("U", "ρ_U(T_6)")],
                "edges": [("π_T(U_3′)", "T_6"), ("U_3′", "ρ_U(T_6)")],
                "rep": [("ρ_U(T_6)", "T_6")],
                "verdict": "Same outcome as today's plain-Git flow (force-push, redispatch), but CloneX made the drop explicit and listed the bot commit being discarded.",
            },
        ],
        "conclusion": "a brought-in rep on top of your commit makes that commit shared. Rewriting it means explicitly dropping the outside work, never silently carrying it along. jj immutability of reps enforces this; <code>cx</code> provides the explicit drop.",
    },
    {
        "id": "S5c",
        "title": "Amended before the bot commit was brought in",
        "repos": [T, U],
        "compositions": ["U"],
        "setup": "Ada amends U_3 to U_3′ before she has brought in the bot's T_5. Then she runs <code>cx fetch</code>.",
        "steps": S5_START[:3] + [
            {
                "title": "Ada amends U_3 to U_3′ (nothing sits on U_3 yet in the umbrella)",
                "cmds": ["ada$ jj squash --into U_3   → U_3′ (same change-id)"],
                "commits": [("U", "U_3′", "red, amended"), ("T", "π_T(U_3′)")],
                "edges": [("U_2", "U_3′"), ("T_4", "π_T(U_3′)")],
                "made": [("U_3′", "π_T(U_3′)")],
                "dim": ["U_3"],
            },
            {
                "title": "Fetching finds T_5, built on a superseded version of Ada's change",
                "cmds": ["ada$ cx fetch trunc", "stale: trunc T_5 (ratchet-bot) was built on π_T(U_3), the old version of your change U_3′; not bringing it in"],
                "dim": ["π_T(U_3)", "T_5"],
                "verdict": "CloneX recognises staleness through the change-id (U_3 and U_3′ are one change), so it doesn't create ρ_U(T_5) or offer a merge. Without a change-id (a plain-Git amend), bringing T_5 in would give an add/add conflict on the test file: loud, not silent.",
            },
        ],
        "conclusion": "staleness is detected when a brought-in commit's rep would sit on a composition commit that a newer version of the same change has superseded.",
    },
    {
        "id": "S3",
        "title": "Bob renames a function in dotsync while Ada uses it from the umbrella",
        "repos": [T, U, D],
        "compositions": ["U"],
        "setup": "dotsync is at D_4. At 09:30 Ada starts on the umbrella and adds config loading to trunc and dotsync; her dotsync code calls <code>load_scopes</code>. At 10:00 Bob, working in dotsync alone on bob-mac, renames <code>load_scopes</code> to <code>read_scopes</code> and pushes. Bob never opens the umbrella.",
        "steps": [
            {
                "title": "Start: the umbrella commit U_4 is where D_4 came in",
                "commits": [("T", "T_4"), ("U", "U_4"), ("D", "D_4")],
                "rep": [("U_4", "D_4")],
                "is": [("U_4", "T_4")],
                "text": "U_4 is D_4's rep. It also <em>is</em> T_4; T_4's rep is an earlier umbrella commit, not shown.",
            },
            {
                "title": "09:45 Ada commits U_5, touching trunc, dotsync and crates/standards",
                "cmds": ["ada$ git commit -am 'Load config in trunc and dotsync'   → U_5"],
                "commits": [("U", "U_5", "Ada"), ("T", "π_T(U_5)"), ("D", "π_D(U_5)")],
                "edges": [("U_4", "U_5"), ("T_4", "π_T(U_5)"), ("D_4", "π_D(U_5)")],
                "made": [("U_5", "π_T(U_5)"), ("U_5", "π_D(U_5)")],
                "text": "Mapping U_5 down gives π_T(U_5) (parent T_4) and π_D(U_5) (parent D_4, adds <code>src/config.rs</code> calling <code>load_scopes</code>). U_5 is the rep of both.",
            },
            {
                "title": "10:00 Bob commits D_5 in dotsync and pushes it",
                "cmds": ["bob$ git commit -am 'Rename load_scopes'   → D_5, parent D_4", "bob$ git push origin main"],
                "commits": [("D", "D_5", "Bob")],
                "edges": [("D_4", "D_5")],
                "text": "This happens on bob-mac and GitHub only. Nothing in the umbrella changes.",
            },
            {
                "title": "10:30 Ada publishes; CloneX tells her dotsync has moved",
                "cmds": [
                    "ada$ cx publish",
                    "trunc:   π_T(U_5) sent (new PR)",
                    "dotsync: π_D(U_5) sent (new PR)",
                    "dotsync: D_5 (Bob, 'Rename load_scopes') is newer than your base D_4 and not in your work",
                ],
                "text": "Publishing copies π_T(U_5) and π_D(U_5) to their repos; the DAG doesn't change. The warning is a DAG fact: D_5 is a dotsync commit that no commit on Ada's line <em>is</em> or descends from (Q-S3b).",
            },
            {
                "title": "Ada creates D_5's rep; it is built on D_4's rep, not on her work",
                "cmds": ["ada$ cx fetch dotsync   → ρ_U(D_5): parent U_4 (rep of D_4), tree = U_4's with tools/dotsync := D_5"],
                "commits": [("U", "ρ_U(D_5)")],
                "edges": [("U_4", "ρ_U(D_5)")],
                "rep": [("ρ_U(D_5)", "D_5")],
                "is": [("ρ_U(D_5)", "T_4")],
                "text": "The same object on every machine that brings D_5 in (S10).",
            },
            {
                "title": "Ada merges it: an ordinary Git merge in the umbrella",
                "cmds": ["ada$ git merge ρ_U(D_5)   → U_6 (clean: Bob changed main.rs, Ada added config.rs)", "ada$ cargo test   → error: cannot find function `load_scopes`"],
                "commits": [("U", "U_6"), ("D", "π_D(U_6)")],
                "edges": [("U_5", "U_6"), ("ρ_U(D_5)", "U_6"), ("π_D(U_5)", "π_D(U_6)"), ("D_5", "π_D(U_6)")],
                "made": [("U_6", "π_D(U_6)")],
                "is": [("U_6", "π_T(U_5)")],
                "text": "The textual merge is clean, and the break shows up <em>in the umbrella</em>, where Ada can fix it (Q-S3c). Mapping U_6 down to dotsync gives π_D(U_6) = merge(π_D(U_5), D_5): in dotsync's terms, Ada's branch merged Bob's work. That is what AGENTS.md already asks for (Q-S3d). trunc didn't change, so U_6 is still π_T(U_5).",
            },
            {
                "title": "Ada fixes the call",
                "cmds": ["ada$ git commit -am 'Use read_scopes'   → U_7"],
                "commits": [("U", "U_7"), ("D", "π_D(U_7)")],
                "edges": [("U_6", "U_7"), ("π_D(U_6)", "π_D(U_7)")],
                "made": [("U_7", "π_D(U_7)")],
                "is": [("U_7", "π_T(U_5)")],
            },
            {
                "title": "Ada publishes again; only dotsync's part changed",
                "cmds": ["ada$ cx publish", "trunc:   unchanged", "dotsync: π_D(U_6), π_D(U_7) added to your PR"],
                "text": "Ada's dotsync PR branch goes π_D(U_5) → π_D(U_6) → π_D(U_7): a fast-forward, adding commits and overwriting nothing (W6). The DAG doesn't change.",
            },
            {
                "title": "Bob merges Ada's dotsync PR on GitHub",
                "cmds": ["github$ merge dotsync PR   → D_6 = merge(D_5, π_D(U_7))"],
                "commits": [("D", "D_6")],
                "edges": [("D_5", "D_6"), ("π_D(U_7)", "D_6")],
                "text": "This is the only moment Bob sees Ada's work: an ordinary PR (W1).",
            },
            {
                "title": "Bringing D_6 in: its rep's parents are ρ_U(D_5) and U_7",
                "cmds": ["ada$ cx fetch dotsync   → ρ_U(D_6): parents ρ_U(D_5), U_7"],
                "commits": [("U", "ρ_U(D_6)")],
                "edges": [("ρ_U(D_5)", "ρ_U(D_6)"), ("U_7", "ρ_U(D_6)")],
                "rep": [("ρ_U(D_6)", "D_6")],
                "is": [("ρ_U(D_6)", "π_T(U_5)")],
                "verdict": "ρ_U(D_5) is already an ancestor of U_7, so the tree outside dotsync is U_7's, and dotsync's content is π_D(U_7)'s, which is D_6's. ρ_U(D_6) is a merge with no content change, a child of U_7. Ada's line just moves forward to it; no merge is needed.",
            },
        ],
        "conclusion": "concurrent work in a tool comes in as its own rep, beside the umbrella's work, and joins it by an ordinary merge. That merge maps down to the tool's ordinary \"merge main into my branch\" commit, and the break shows up where the author can fix it. Bob sees only Ada's PR.",
    },
    {
        "id": "S6",
        "title": "Two copies of tdd-ratchet, one CVE fix",
        "repos": [U, ("R", "tdd-ratchet")],
        "compositions": ["U"],
        "setup": "tdd-ratchet (R) appears twice in the umbrella. Occurrence R1 is <code>tools/tdd-ratchet/</code>, at R_7. Max adds occurrence R2, <code>fixtures/tdd-ratchet-1.1.6/</code>, frozen at v1.1.6 (R_6), for the ledger compatibility tests. Later a CVE needs fixing in both. Every tool commit gets one rep per occurrence, so π and ρ are subscripted by the occurrence.",
        "steps": [
            {
                "title": "Start: one occurrence, R1 at tools/",
                "commits": [("R", "R_5"), ("R", "R_6", "v1.1.6"), ("R", "R_7"), ("U", "ρ_U.R1(R_5)"), ("U", "ρ_U.R1(R_6)"), ("U", "ρ_U.R1(R_7)")],
                "edges": [("R_5", "R_6"), ("R_6", "R_7"), ("ρ_U.R1(R_5)", "ρ_U.R1(R_6)"), ("ρ_U.R1(R_6)", "ρ_U.R1(R_7)")],
                "rep": [("ρ_U.R1(R_5)", "R_5", "R1"), ("ρ_U.R1(R_6)", "R_6", "R1"), ("ρ_U.R1(R_7)", "R_7", "R1")],
                "text": "Each tdd-ratchet commit has its rep at R1. R_5 stands for all of tdd-ratchet's history before v1.1.6.",
            },
            {
                "title": "Max adds occurrence R2: reps of its history, built on ρ_U.R1(R_7)",
                "cmds": ["max$ cx add fixtures/tdd-ratchet-1.1.6 --from tdd-ratchet@v1.1.6   → ρ_U.R2(R_5), ρ_U.R2(R_6)"],
                "commits": [("U", "ρ_U.R2(R_5)"), ("U", "ρ_U.R2(R_6)")],
                "edges": [("ρ_U.R1(R_7)", "ρ_U.R2(R_5)"), ("ρ_U.R2(R_5)", "ρ_U.R2(R_6)")],
                "rep": [("ρ_U.R2(R_5)", "R_5", "R2"), ("ρ_U.R2(R_6)", "R_6", "R2")],
                "is": [("ρ_U.R2(R_5)", "R_7", "R1"), ("ρ_U.R2(R_6)", "R_7", "R1")],
                "text": "The same rule as converting a submodule (S15): history from before the occurrence existed gets reps built on the commit it is added to. Each is ρ_U.R1(R_7)'s tree plus the fixture at that commit. Max's line just moves forward to ρ_U.R2(R_6): no merge. <code>git blame fixtures/tdd-ratchet-1.1.6/src/ledger.rs</code> names the real authors (W8). Cost: one umbrella commit per tdd-ratchet commit up to v1.1.6. \"Syncing never moves it\" (Q-S6b) is about which label R2 follows, so it is level 2.",
            },
            {
                "title": "Max fixes the CVE in both copies in one umbrella commit U_1",
                "cmds": ["max$ git commit -am 'Reject oversized ledger entries (CVE-2026-1234)'   → U_1"],
                "commits": [("U", "U_1", "CVE fix"), ("R", "π_R1(U_1)"), ("R", "π_R2(U_1)")],
                "edges": [("ρ_U.R2(R_6)", "U_1"), ("R_7", "π_R1(U_1)"), ("R_6", "π_R2(U_1)")],
                "made": [("U_1", "π_R1(U_1)", "R1"), ("U_1", "π_R2(U_1)", "R2")],
                "text": "Mapping U_1 down at R1 gives π_R1(U_1) (parent R_7); at R2 it gives π_R2(U_1) (parent R_6). They are two different tdd-ratchet commits, with the same message, author and date, so recognisably the same fix (Q-S6c). U_1 is the rep of both, as the owner's model says.",
            },
            {
                "title": "Max publishes: one PR on the current line, one backport on v1.1.6",
                "cmds": ["max$ cx publish", "tdd-ratchet: π_R1(U_1) sent (new PR)", "tdd-ratchet: π_R2(U_1) sent (new branch on v1.1.6)"],
                "text": "The DAG doesn't change. Which branch names they get is level 2.",
            },
            {
                "title": "tdd-ratchet merges π_R1(U_1) (R_8) and tags π_R2(U_1) as v1.1.7",
                "cmds": ["github$ merge PR   → R_8 = merge(R_7, π_R1(U_1))", "max$ git tag v1.1.7 π_R2(U_1) && git push --tags   (a label; no new commit)"],
                "commits": [("R", "R_8")],
                "edges": [("R_7", "R_8"), ("π_R1(U_1)", "R_8")],
            },
            {
                "title": "Bringing R_8 in at R1: its rep contains R2's fix too",
                "cmds": ["max$ cx fetch tdd-ratchet   → ρ_U.R1(R_8): parents ρ_U.R1(R_7), U_1"],
                "commits": [("U", "ρ_U.R1(R_8)")],
                "edges": [("ρ_U.R1(R_7)", "ρ_U.R1(R_8)"), ("U_1", "ρ_U.R1(R_8)")],
                "rep": [("ρ_U.R1(R_8)", "R_8", "R1")],
                "is": [("ρ_U.R1(R_8)", "π_R2(U_1)", "R2")],
                "verdict": "Outside tools/tdd-ratchet/, ρ_U.R1(R_8)'s tree is Git's merge of ρ_U.R1(R_7) and U_1, which is U_1's, so at R2 it <em>is</em> π_R2(U_1). That is consistent: the fix is in both copies. v1.1.7 needs nothing brought in; π_R2(U_1)'s rep is already U_1.",
            },
        ],
        "conclusion": "a tool at two paths is two occurrences; reps are per tool commit <em>per occurrence</em>. One umbrella commit can be the rep of two commits of the same tool, one per occurrence. Adding an occurrence builds reps for its history on the commit it is added to, like conversion. Rename and copy detection don't pair the two copies, because neither path is deleted.",
    },
    {
        "id": "S7",
        "title": "tb's history is rewritten (the ledger repair)",
        "repos": [U, ("B", "tb")],
        "compositions": ["U"],
        "setup": "tb's B_2 edited the ledger badly. With Max's approval, tb's history from B_2 on is rebuilt as B_2′, B_3′: the same trees except the ledger. The old tip is tagged <code>backup/tb-main-2026-09-09</code>, and tb's main is force-pushed. The umbrella must not rewrite.",
        "steps": s7_steps("U_2"),
        "conclusion": "a rewrite comes in as new reps beside the old ones, joined by one merge. That merge records which tool commit replaces which, and uses the replaced commit as the base, so there are no spurious conflicts and no resurrection of the old history. The umbrella's history is never rewritten.",
    },
    {
        "id": "S7a",
        "title": "Ada had tb work in flight during the rewrite",
        "repos": [U, ("B", "tb")],
        "compositions": ["U"],
        "setup": "S7 again, but before the rewrite Ada committed U_2 on U_1, changing <code>tools/tb/src/pane.rs</code>, and published it as a PR in tb. The PR hasn't merged when tb is rewritten.",
        "steps": s7_steps("U_3")[:1] + [
            {
                "title": "Before the rewrite, Ada commits U_2 in the umbrella and publishes π_B(U_2)",
                "cmds": ["ada$ git commit -am 'Handle closed panes'   → U_2", "ada$ cx publish   → tb: π_B(U_2) sent (new PR)"],
                "commits": [("U", "U_2", "Ada"), ("B", "π_B(U_2)")],
                "edges": [("U_1", "U_2"), ("B_3", "π_B(U_2)")],
                "made": [("U_2", "π_B(U_2)")],
            },
        ] + s7_steps("U_3")[1:] + [
            {
                "title": "Ada merges U_3 into her line; her tb change is rebuilt on B_3′",
                "cmds": ["ada$ git merge U_3   → U_4 (tools/tb: B_3 → B_3′ from U_3, plus U_2's pane.rs change: clean)"],
                "commits": [("U", "U_4"), ("B", "π_B(U_4)")],
                "edges": [("U_2", "U_4"), ("U_3", "U_4"), ("B_3′", "π_B(U_4)")],
                "made": [("U_4", "π_B(U_4)")],
                "dim": ["π_B(U_2)"],
                "text": "Here the ordinary merge is right: its base is U_1, whose tools/tb is B_3, so it applies U_2's change on top of B_3′. Mapping U_4 down, with U_3's record that B_3′ replaces B_3, treats π_B(U_2) as built on a replaced commit and regenerates it on the replacement: π_B(U_4), parent B_3′, with U_2's message and author. That is what jj does to the descendants of a rewritten commit.",
                "verdict": "Republishing updates Ada's own PR branch from π_B(U_2) to π_B(U_4), replacing only her own commit, as anyone must after an upstream force-push. The alternative mapping, merge(π_B(U_2), B_3′), would carry B_2 and B_3 back into tb through her PR.",
            },
        ],
        "conclusion": "(candidate rule) a tool commit built on a replaced commit is regenerated on its replacement when mapped through a merge that records the replacement. This needs its own attack before it is trusted: who may record a replacement, and what if it is wrong (the forged-claim story).",
    },
]
