"""Stories as data for storydags.py. Every step lists exactly what it adds.

Node ids are mermaid ids (ASCII); labels are what the reader sees.
Placement rule under test (C″): an outside tool commit's composition commit
is built on the composition commit that is the *rep* of its tool parent;
for tool merges, the tree outside the tool path is Git's merge of the
parents' reps' trees. A tool commit published from composition commit u
has u as its rep (W14). "Bringing in" is two explicit steps: create the
rep (deterministic, like a fetch), then an ordinary merge.
"""

TR = ("TR", "trunc repo")
DS = ("DS", "dotsync repo")
UM = ("UM", "umbrella repo")


S5_START = [
    {
        "title": "Start",
        "commits": [("TR", "t4", "t4"), ("UM", "U2", "U2")],
        "rep": [("U2", "t4")],
    },
    {
        "title": "Ada commits the red (test) change in the umbrella",
        "cmds": ["ada$ git commit -m 'Add failing test for --config'   → r (changes tools/trunc/tests/)"],
        "commits": [("UM", "r", "r (red)"), ("TR", "xr", "x_r")],
        "edges": [("U2", "r"), ("t4", "xr")],
        "made": [("r", "xr")],
        "text": "Mapping r down gives x_r, parent t4. Publishing copies x_r to trunc; the DAG doesn't change.",
    },
    {
        "title": "ratchet-bot commits b on x_r in trunc",
        "cmds": ["ada$ gh workflow run ledger.yml --ref main -f target=13", "bot$ commit .test-status.json: pending   → b, parent x_r"],
        "commits": [("TR", "b", "b (bot)")],
        "edges": [("xr", "b")],
    },
    {
        "title": "Ada brings b in; its rep sits directly on her own commit r",
        "cmds": ["ada$ cx fetch trunc   → ρ(b): parent r (the rep of x_r), tree = r's with tools/trunc := b"],
        "commits": [("UM", "r_b", "ρ(b)")],
        "edges": [("r", "r_b")],
        "rep": [("r_b", "b")],
        "text": "ρ(b) descends from r, so Ada's line simply continues from ρ(b). No merge is needed. From now on r has someone else's work on top of it: it is <em>shared</em>.",
    },
]

S7_STEPS = [
    {
        "title": "Start: the umbrella has reps of e1, e2, e3, and more work on top (U6)",
        "commits": [("TBR", "e1", "e1"), ("TBR", "e2", "e2 (bad ledger)"), ("TBR", "e3", "e3"), ("UM", "R1", "ρ(e1)"), ("UM", "R2", "ρ(e2)"), ("UM", "R3", "ρ(e3)"), ("UM", "U6", "U6")],
        "edges": [("e1", "e2"), ("e2", "e3"), ("R1", "R2"), ("R2", "R3"), ("R3", "U6")],
        "rep": [("R1", "e1"), ("R2", "e2"), ("R3", "e3")],
        "is": [("U6", "e3")],
        "text": "U6 changes only the umbrella's README, so it <em>is</em> e3.",
    },
    {
        "title": "tb is rewritten: e2′, e3′ replace e2, e3",
        "cmds": ["max$ (in tb) rebuild from e2 with repaired ledgers   → e2′, e3′", "max$ git tag backup/tb-main-2026-09-09 e3 && git push --force origin main"],
        "commits": [("TBR", "e2b", "e2′"), ("TBR", "e3b", "e3′")],
        "edges": [("e1", "e2b"), ("e2b", "e3b")],
        "dim": ["e2", "e3"],
        "text": "e2 and e3 still exist (the backup tag holds them), but no one's work continues from them. The umbrella's R2, R3 and U6 are untouched: checking out U6 still works offline, because its tree has the files (Q-S7a).",
    },
    {
        "title": "Max creates reps for the new history, built on e1's rep",
        "cmds": ["max$ cx fetch tb   → ρ(e2′) on ρ(e1), ρ(e3′) on ρ(e2′)", "tb: e3′ replaces e3 (tb's main moved from e3 to e3′ without containing it)"],
        "commits": [("UM", "R2b", "ρ(e2′)"), ("UM", "R3b", "ρ(e3′)")],
        "edges": [("R1", "R2b"), ("R2b", "R3b")],
        "rep": [("R2b", "e2b"), ("R3b", "e3b")],
        "text": "\"e3′ replaces e3\" comes from how tb's label moved, which is level-2 information. At level 1, CloneX takes it as an input (or Max states it).",
    },
    {
        "title": "Max merges it, with e3 as the base for tools/tb",
        "cmds": ["max$ cx merge tb   → M, trailer: Clonex-Supersedes: tools/tb e3 e3′"],
        "commits": [("UM", "M", "M")],
        "edges": [("U6", "M"), ("R3b", "M")],
        "is": [("M", "e3b")],
        "hazard": "A plain <code>git merge</code> uses ρ(e1) as the base. Both sides changed the ledger since e1, differently, so it conflicts in <code>.test-status.json</code>, a file the umbrella never touched. And a plain lens would map M down to a new tb commit merge(e3, e3′), which would put the bad history back into tb if anyone published it.",
        "verdict": "CloneX's merge uses the replaced commit e3 as the base for tools/tb. The umbrella's side is exactly e3, so tools/tb simply becomes e3′, with no conflict (Q-S7b). The trailer is recorded in M, so every machine maps M down the same way: M <em>is</em> e3′ (Q-S2e). It names commits, not labels (D1).",
    },
]

STORIES = [
    {
        "id": "S2b",
        "title": "Half-landed cross-tool change",
        "repos": [TR, UM, DS],
        "compositions": ["UM"],
        "setup": "Max makes one umbrella commit <code>u</code> that changes trunc and dotsync. trunc merges its part first; dotsync later.",
        "steps": [
            {
                "title": "Start: the umbrella contains trunc at t4 and dotsync at d2",
                "commits": [("TR", "t4", "t4"), ("UM", "U3", "U3"), ("DS", "d2", "d2")],
                "is": [("U3", "t4"), ("U3", "d2")],
                "text": "The reps of t4 and d2 are earlier umbrella commits, not shown.",
            },
            {
                "title": "Max commits u in the umbrella; u is the rep of two tool commits",
                "cmds": ["max$ git commit -am 'Alias AGENTS.md as CLAUDE.md everywhere'"],
                "commits": [("UM", "u", "u"), ("TR", "xT", "x_T"), ("DS", "xD", "x_D")],
                "edges": [("U3", "u"), ("t4", "xT"), ("d2", "xD")],
                "made": [("u", "xT"), ("u", "xD")],
                "text": "Mapping <code>u</code> down gives <code>x_T</code> (parent t4) and <code>x_D</code> (parent d2). They were made from u, so u is their rep (W14).",
            },
            {
                "title": "trunc merges its part (t6); its rep ρ(t6) is created",
                "cmds": ["github$ merge trunc PR #13  → t6 = merge(t4, x_T)", "max$ cx fetch trunc          → creates ρ(t6)"],
                "commits": [("TR", "t6", "t6"), ("UM", "r_t6", "ρ(t6)")],
                "edges": [("t4", "t6"), ("xT", "t6"), ("U3", "r_t6"), ("u", "r_t6")],
                "rep": [("r_t6", "t6")],
                "is": [("r_t6", "xD")],
                "verdict": "ρ(t6)'s parents are the reps of t6's parents: U3 (for t4) and u (for x_T). Its tree outside trunc is Git's merge of U3 and u, which is u's. So it contains all of u. That's consistent: it <em>is</em> x_D in dotsync. Whether a label should point here is level 2.",
            },
            {
                "title": "Jim's j1 lands on trunc; its rep is built on t6's rep",
                "cmds": ["github$ merge trunc PR #14  → j1 (Jim), parent t6", "max$ cx fetch trunc          → creates ρ(j1) on ρ(t6)"],
                "commits": [("TR", "j1", "j1"), ("UM", "r_j1", "ρ(j1)")],
                "edges": [("t6", "j1"), ("r_t6", "r_j1")],
                "rep": [("r_j1", "j1")],
                "is": [("r_j1", "xD")],
            },
            {
                "title": "dotsync merges its part (d4); the umbrella now has two divergent lines",
                "cmds": ["github$ merge dotsync PR #51 → d4 = merge(d2, x_D)", "max$ cx fetch dotsync        → creates ρ(d4)"],
                "commits": [("DS", "d4", "d4"), ("UM", "r_d4", "ρ(d4)")],
                "edges": [("d2", "d4"), ("xD", "d4"), ("U3", "r_d4"), ("u", "r_d4")],
                "rep": [("r_d4", "d4")],
                "is": [("r_d4", "xT")],
                "verdict": "Nothing joins ρ(j1) and ρ(d4) yet. No umbrella commit contains both tools' latest. That's normal divergence, and every commit is still one real commit of each tool.",
            },
            {
                "title": "Someone explicitly merges the two lines in the umbrella",
                "cmds": ["max$ git merge ρ(d4)          (while on ρ(j1)'s line) → M"],
                "commits": [("UM", "M", "M")],
                "edges": [("r_j1", "M"), ("r_d4", "M")],
                "is": [("M", "j1"), ("M", "d4")],
                "verdict": "Clean: the shared ancestor is u, and each side changed a different tool since then.",
            },
        ],
        "conclusion": "every tool commit gets exactly one rep; a rep's parents are its tool parents' reps; the umbrella never follows a tool implicitly. Its commits join by explicit merges.",
    },
    {
        "id": "S10",
        "title": "Ada and Max bring in the same commit",
        "repos": [TR, UM],
        "compositions": ["UM"],
        "setup": "Ada and Max each have their own umbrella commit on U2 (Ada edits README, Max edits crates/). Jim's typo fix j1 lands on trunc. Each of them brings it in on their own machine.",
        "steps": [
            {
                "title": "Start",
                "commits": [("TR", "t4", "t4"), ("UM", "U2", "U2"), ("UM", "a", "a (Ada)"), ("UM", "m", "m (Max)")],
                "edges": [("U2", "a"), ("U2", "m")],
                "rep": [("U2", "t4")],
                "is": [("a", "t4"), ("m", "t4")],
                "text": "U2 is the rep of t4. a and m don't touch trunc, so both <em>are</em> t4 too, but neither is its rep.",
            },
            {
                "title": "Jim's fix j1 lands on trunc",
                "commits": [("TR", "j1", "j1 (Jim)")],
                "edges": [("t4", "j1")],
            },
            {
                "title": "Ada's machine creates j1's rep",
                "cmds": ["ada$ cx fetch trunc   → ρ(j1): parent U2 (rep of t4), tree = U2's tree with tools/trunc := j1"],
                "commits": [("UM", "r_j1", "ρ(j1)")],
                "edges": [("U2", "r_j1")],
                "rep": [("r_j1", "j1")],
            },
            {
                "title": "Ada merges it explicitly",
                "cmds": ["ada$ git merge ρ(j1)   → A1"],
                "commits": [("UM", "A1", "A1")],
                "edges": [("a", "A1"), ("r_j1", "A1")],
                "is": [("A1", "j1")],
            },
            {
                "title": "Max's machine creates j1's rep: the identical object, so no new commit",
                "cmds": ["max$ cx fetch trunc   → ρ(j1) again: same parent, tree, author, message → same SHA"],
                "text": "The DAG doesn't change. Max's copy of ρ(j1) is byte-for-byte Ada's, because every input to it (j1, U2) is shared.",
            },
            {
                "title": "Max merges it explicitly",
                "cmds": ["max$ git merge ρ(j1)   → M1"],
                "commits": [("UM", "M1", "M1")],
                "edges": [("m", "M1"), ("r_j1", "M1")],
                "is": [("M1", "j1")],
            },
            {
                "title": "Their lines are merged",
                "cmds": ["max$ git merge A1   → X"],
                "commits": [("UM", "X", "X")],
                "edges": [("M1", "X"), ("A1", "X")],
                "is": [("X", "j1")],
                "verdict": "The shared ancestor includes ρ(j1), so Jim's fix is one commit in the umbrella's history. A later trunc revert of j1 merges correctly (the duplicate hazard can't arise).",
            },
        ],
        "conclusion": "a rep is a function of the tool commit and its parent's rep only, so every machine creates the same one. Bringing in is create-rep, then explicit merge.",
    },
    {
        "id": "S11",
        "title": "Ada rebases with plain Git",
        "repos": [TR, UM],
        "compositions": ["UM"],
        "setup": "Continuing S10 before step 5. Ada wants her work on top of Max's m instead of U2, and runs plain <code>git rebase</code>.",
        "steps": [
            {
                "title": "Start",
                "commits": [("TR", "t4", "t4"), ("TR", "j1", "j1 (Jim)"), ("UM", "U2", "U2"), ("UM", "a", "a (Ada)"), ("UM", "m", "m (Max)"), ("UM", "r_j1", "ρ(j1)"), ("UM", "A1", "A1")],
                "edges": [("t4", "j1"), ("U2", "a"), ("U2", "m"), ("U2", "r_j1"), ("a", "A1"), ("r_j1", "A1")],
                "rep": [("U2", "t4"), ("r_j1", "j1")],
                "is": [("a", "t4"), ("m", "t4"), ("A1", "j1")],
            },
            {
                "title": "git rebase m replays a and ρ(j1) as new commits (the merge is dropped)",
                "cmds": ["ada$ git rebase m   (from A1)"],
                "commits": [("UM", "a2", "a′"), ("UM", "r_j1b", "ρ′(j1)")],
                "edges": [("m", "a2"), ("a2", "r_j1b")],
                "is": [("a2", "t4"), ("r_j1b", "j1")],
                "dim": ["a", "A1"],
                "hazard": "ρ′(j1) has the same trunc content, author and message as j1, so it still <em>is</em> j1, but it is a second umbrella commit for j1. If another line (Max's M1) has the real rep ρ(j1), merging the two brings back the duplicate hazard: a trunc revert of j1 could be undone.",
            },
            {
                "title": "What should have happened: move only Ada's own commit, keep the merge",
                "cmds": ["ada$ jj rebase -s a -d m   (or: git rebase of a alone, then git merge ρ(j1))"],
                "commits": [("UM", "a3", "a″"), ("UM", "A3", "A1″")],
                "edges": [("m", "a3"), ("a3", "A3"), ("r_j1", "A3")],
                "is": [("a3", "t4"), ("A3", "j1")],
                "dim": ["a2", "r_j1b"],
                "verdict": "ρ(j1) is untouched and still the only rep. jj's rebase keeps merges. Plain git rebase linearises them, so CloneX must detect ρ′(j1) (\"a second umbrella commit for trunc j1\") and offer this repair.",
            },
        ],
        "conclusion": "reps must never be rebased; a rebase that copies one creates a duplicate. Needs detection in <code>cx status</code>, and jj should treat reps as immutable. Plain <code>git rebase</code> is a hazard to document.",
    },
    {
        "id": "S12",
        "title": "GitHub squash-merges an umbrella PR",
        "repos": [TR, UM],
        "compositions": ["UM"],
        "setup": "Ada's PR head is A1 (her README change merged with ρ(j1)). Nothing else in the umbrella has j1 yet. GitHub's squash button makes one new commit S on top of m.",
        "steps": [
            {
                "title": "Start",
                "commits": [("TR", "t4", "t4"), ("TR", "j1", "j1 (Jim)"), ("UM", "U2", "U2"), ("UM", "a", "a (Ada)"), ("UM", "m", "m"), ("UM", "r_j1", "ρ(j1)"), ("UM", "A1", "A1")],
                "edges": [("t4", "j1"), ("U2", "a"), ("U2", "m"), ("U2", "r_j1"), ("a", "A1"), ("r_j1", "A1")],
                "rep": [("U2", "t4"), ("r_j1", "j1")],
                "is": [("a", "t4"), ("m", "t4"), ("A1", "j1")],
            },
            {
                "title": "Squash: S has one parent (m) and A1's combined changes",
                "cmds": ["github$ squash-merge Ada's PR   → S (author Ada), parent m"],
                "commits": [("UM", "S", "S")],
                "edges": [("m", "S")],
                "is": [("S", "j1")],
                "dim": ["a", "A1"],
                "hazard": "S changes tools/trunc from t4 to j1's content, but it isn't j1's rep. Its message carries ρ(j1)'s <code>Clonex-Source</code> line, and the content matches, so CloneX can prove S <em>is</em> j1: publishing won't push a copy of Jim's fix authored by Ada. But the umbrella's history now has Jim's change inside S, and merging S's line with a line that has the real ρ(j1) brings back the duplicate hazard. A merge commit instead of a squash avoids all of this.",
            },
        ],
        "conclusion": "squash merges of umbrella PRs hide reps inside a new commit. Merge-commit-only (the owner's preference) keeps every rep in the DAG. CloneX must still prove S is j1 by content and trailer, so it never publishes a false copy.",
    },
    {
        "id": "S13",
        "title": "Extract crates/standards into its own repo",
        "repos": [("CC", "crosscut repo (new)"), UM],
        "compositions": ["UM"],
        "setup": "The umbrella's own directory <code>crates/standards</code> becomes a new repo, crosscut, keeping its history. Later an outsider, Olga, contributes to crosscut directly.",
        "steps": [
            {
                "title": "Start: three umbrella commits, two of which touch crates/standards",
                "commits": [("UM", "U1", "U1"), ("UM", "U2", "U2"), ("UM", "U3", "U3")],
                "edges": [("U1", "U2"), ("U2", "U3")],
                "text": "U1 adds standards v1; U2 edits only the README; U3 edits standards and the README.",
            },
            {
                "title": "Derive crosscut's history: the umbrella commits are its reps",
                "cmds": ["max$ cx extract crates/standards   → k1 (from U1), k2 (from U3)"],
                "commits": [("CC", "k1", "k1"), ("CC", "k2", "k2")],
                "edges": [("k1", "k2")],
                "made": [("U1", "k1"), ("U3", "k2")],
                "is": [("U2", "k1")],
                "text": "k1 and k2 were made from U1 and U3, so those are their reps (W14). U2 changes nothing in standards, so it <em>is</em> k1 without being its rep. No new umbrella commits.",
            },
            {
                "title": "Meanwhile the umbrella moves on (U4), and Olga commits o1 to crosscut",
                "commits": [("UM", "U4", "U4"), ("CC", "o1", "o1 (Olga)")],
                "edges": [("U3", "U4"), ("k2", "o1")],
                "is": [("U4", "k2")],
            },
            {
                "title": "o1's rep is built on k2's rep (U3), a full umbrella state",
                "cmds": ["max$ cx fetch crosscut   → ρ(o1): parent U3, tree = U3's with crates/standards := o1"],
                "commits": [("UM", "r_o1", "ρ(o1)")],
                "edges": [("U3", "r_o1")],
                "rep": [("r_o1", "o1")],
            },
            {
                "title": "Explicit merge into the umbrella's current work",
                "cmds": ["max$ git merge ρ(o1)   (on U4) → U5"],
                "commits": [("UM", "U5", "U5")],
                "edges": [("U4", "U5"), ("r_o1", "U5")],
                "is": [("U5", "o1")],
                "verdict": "ρ(o1) looks like an ordinary side branch from U3 that changed only crates/standards; its merge base with U4 is U3, a real full state.",
            },
        ],
        "conclusion": "extraction needs no new umbrella commits: the existing ones become reps. The same placement rule covers later outside commits, and a composition-made rep has a full tree, so it's a good merge base.",
    },
    {
        "id": "S15",
        "title": "Convert a submodule umbrella",
        "repos": [TR, UM],
        "compositions": ["UM"],
        "setup": "Today's umbrella: u1 adds the submodule (gitlink → t2), u2 bumps it (gitlink → t4). Converting must keep u1 and u2 untouched and give the umbrella trunc's real history.",
        "steps": [
            {
                "title": "Start: gitlinks only",
                "commits": [("TR", "t1", "t1"), ("TR", "t2", "t2"), ("TR", "t3", "t3"), ("TR", "t4", "t4"), ("UM", "u1", "u1"), ("UM", "u2", "u2")],
                "edges": [("t1", "t2"), ("t2", "t3"), ("t3", "t4"), ("u1", "u2")],
                "text": "u1 and u2 contain a gitlink, not files. There's no \"is\" line: a gitlink is a pointer, not content.",
            },
            {
                "title": "Create reps for trunc's history, built on the commit being converted",
                "cmds": ["max$ cx adopt tools/trunc   (on u2) → ρ(t1)…ρ(t4)"],
                "commits": [("UM", "r_t1", "ρ(t1)"), ("UM", "r_t2", "ρ(t2)"), ("UM", "r_t3", "ρ(t3)"), ("UM", "r_t4", "ρ(t4)")],
                "edges": [("u2", "r_t1"), ("r_t1", "r_t2"), ("r_t2", "r_t3"), ("r_t3", "r_t4")],
                "rep": [("r_t1", "t1"), ("r_t2", "t2"), ("r_t3", "t3"), ("r_t4", "t4")],
                "text": "trunc's root t1 has no parent rep, so its rep is built on u2, the commit being converted: u2's tree with the gitlink replaced by t1's files. Every rep is a full umbrella state. <code>git log -- tools/trunc</code> now shows all of trunc's commits, with their authors.",
            },
            {
                "title": "The conversion commit",
                "cmds": ["max$ git merge ρ(t4) && git rm .gitmodules entry   → C"],
                "commits": [("UM", "C", "C")],
                "edges": [("r_t4", "C")],
                "is": [("C", "t4")],
                "verdict": "u1 and u2 are unchanged (checking them out still needs the submodule, as it always did). From C on, trunc's files are ordinary files. The same inputs (u2, trunc's history) give the same reps on every machine.",
            },
        ],
        "conclusion": "history before containment gets reps built on the first containing commit, so reps always have full trees. The old umbrella history is never rewritten.",
    },
    {
        "id": "S17",
        "title": "A throwaway composition for an agent",
        "repos": [DS, ("VV", "view repo V (local only)"), ("AH", "agent-harness repo")],
        "compositions": ["VV"],
        "setup": "Ada needs dotsync and agent-harness side by side for one task, in a new composition V that exists only on her machine.",
        "steps": [
            {
                "title": "Start: two tool repos, V empty",
                "commits": [("DS", "d1", "d1"), ("DS", "d2", "d2"), ("AH", "h1", "h1")],
                "edges": [("d1", "d2")],
            },
            {
                "title": "Create reps for both histories",
                "cmds": ["ada$ cx new V --with dotsync --with agent-harness"],
                "commits": [("VV", "v_d1", "ρ(d1)"), ("VV", "v_d2", "ρ(d2)"), ("VV", "v_h1", "ρ(h1)")],
                "edges": [("v_d1", "v_d2")],
                "rep": [("v_d1", "d1"), ("v_d2", "d2"), ("v_h1", "h1")],
                "hazard": "V has no earlier commit to build on, so these first reps contain only their own tool's directory. They are real V states, since V holds nothing else yet, but they are partial trees. A later merge whose base is ρ(d2) sees agent-harness's files as \"added\", the narrow rename-detection residual (G1). CloneX's own merges avoid it; plain <code>git revert</code> of ρ(d2) inside V would not.",
            },
            {
                "title": "V's first ordinary commit joins them",
                "cmds": ["ada$ git merge --allow-unrelated-histories   → V0"],
                "commits": [("VV", "V0", "V0")],
                "edges": [("v_d2", "V0"), ("v_h1", "V0")],
                "is": [("V0", "d2"), ("V0", "h1")],
            },
            {
                "title": "Ada's change across both tools is one V commit, the rep of two tool commits",
                "cmds": ["ada$ git commit -am 'Wire harness to dotsync config'   → w"],
                "commits": [("VV", "w", "w"), ("DS", "xD", "x_D"), ("AH", "xH", "x_H")],
                "edges": [("V0", "w"), ("d2", "xD"), ("h1", "xH")],
                "made": [("w", "xD"), ("w", "xH")],
                "verdict": "Publishing sends x_D and x_H to their repos. V can then be deleted. Nothing of Ada's work lives only in V once both are published.",
            },
        ],
        "conclusion": "throwaway compositions work unchanged, except that the very first reps have partial trees (a documented residual). Safe to discard V is a checkable property: no V commit is the rep of an unpublished tool commit.",
    },
    {
        "id": "S5",
        "title": "Ratchet flow: red, bot, green",
        "repos": [TR, UM],
        "compositions": ["UM"],
        "setup": "Ada adds a test and then the implementation from the umbrella. trunc's ratchet needs red, then the bot's ledger commit, then green, in trunc's own history.",
        "steps": S5_START + [
            {
                "title": "Ada commits green on top of ρ(b)",
                "cmds": ["ada$ git commit -m 'Implement --config'   → g (parent ρ(b))"],
                "commits": [("UM", "g", "g (green)"), ("TR", "xg", "x_g")],
                "edges": [("r_b", "g"), ("b", "xg")],
                "made": [("g", "xg")],
                "verdict": "trunc's history is x_r → b → x_g: red, bot, green, exactly as the ratchet requires. The bot records passing next, and it arrives the same way b did.",
            },
        ],
        "conclusion": "a bot commit on your published commit comes back as a rep sitting directly on your own commit, with no merge needed. The order in the tool is preserved by construction.",
    },
    {
        "id": "S5a",
        "title": "Reviewer asks for a test change: fix forward",
        "repos": [TR, UM],
        "compositions": ["UM"],
        "setup": "After step 3 of S5, the reviewer asks for a change to the test. Ada fixes it with a new commit (append-only).",
        "steps": S5_START + [
            {
                "title": "Ada commits the test fix on top of ρ(b)",
                "cmds": ["ada$ git commit -m 'Tighten the --config test'   → r2 (parent ρ(b))"],
                "commits": [("UM", "r2", "r2"), ("TR", "xr2", "x_r2")],
                "edges": [("r_b", "r2"), ("b", "xr2")],
                "made": [("r2", "xr2")],
                "verdict": "Nothing special. trunc gets x_r → b → x_r2, the bot runs again on top, and the flow continues. This is the path that needs no machinery.",
            },
        ],
        "conclusion": "append-only fixes after outside work has built on yours need nothing new.",
    },
    {
        "id": "S5b",
        "title": "Reviewer asks for a test change: amend",
        "repos": [TR, UM],
        "compositions": ["UM"],
        "setup": "After step 3 of S5, Ada wants to amend r itself rather than add a commit.",
        "steps": S5_START + [
            {
                "title": "jj refuses: r has outside work on top",
                "cmds": ["ada$ jj squash --into r   (with the edited test)", "Error: Commit ρ(b) is immutable  (reps are immutable heads, so r, its ancestor, is too)"],
                "text": "The DAG doesn't change.",
                "hazard": "Without that refusal, jj would rebase ρ(b) onto the amended r. The result would be a commit authored by the bot, recording a ledger for a test the bot never saw. Mapped down, it is not b, so publishing would push a forged bot commit into trunc. The refusal is what makes the choice explicit.",
            },
            {
                "title": "Ada explicitly drops the outside work above r, then amends",
                "cmds": ["ada$ cx drop-above r    (abandons ρ(b); CloneX lists what's dropped: trunc b, by ratchet-bot)", "ada$ jj squash --into r   → r′"],
                "commits": [("UM", "r2", "r′"), ("TR", "xr2", "x_r′")],
                "edges": [("U2", "r2"), ("t4", "xr2")],
                "made": [("r2", "xr2")],
                "dim": ["r", "r_b", "xr", "b"],
                "text": "r′ has the same jj change-id as r, so CloneX knows it supersedes r. In trunc, x_r and b are now stale, and publishing replaces them. That is the force-update of the PR branch Ada would do today.",
            },
            {
                "title": "The bot reruns on x_r′; Ada brings it in",
                "cmds": ["ada$ cx publish && gh workflow run ledger.yml ...", "bot$ → b′ on x_r′", "ada$ cx fetch trunc   → ρ(b′) on r′"],
                "commits": [("TR", "b2", "b′ (bot)"), ("UM", "r_b2", "ρ(b′)")],
                "edges": [("xr2", "b2"), ("r2", "r_b2")],
                "rep": [("r_b2", "b2")],
                "verdict": "Same outcome as today's plain-Git flow (force-push, redispatch), but CloneX made the drop explicit and listed the bot commit being discarded.",
            },
        ],
        "conclusion": "a brought-in rep on top of your commit makes that commit shared. Rewriting it means explicitly dropping the outside work, never silently carrying it along. jj immutability of reps enforces this; <code>cx</code> provides the explicit drop.",
    },
    {
        "id": "S5c",
        "title": "Amended before the bot commit was brought in",
        "repos": [TR, UM],
        "compositions": ["UM"],
        "setup": "Ada amends r to r′ before she has brought in the bot's b. Then she runs <code>cx fetch</code>.",
        "steps": S5_START[:3] + [
            {
                "title": "Ada amends r to r′ (nothing sits on r yet in the umbrella)",
                "cmds": ["ada$ jj squash --into r   → r′ (same change-id)"],
                "commits": [("UM", "r2", "r′"), ("TR", "xr2", "x_r′")],
                "edges": [("U2", "r2"), ("t4", "xr2")],
                "made": [("r2", "xr2")],
                "dim": ["r"],
            },
            {
                "title": "Fetching finds b, built on a superseded version of Ada's change",
                "cmds": ["ada$ cx fetch trunc", "stale: trunc b (ratchet-bot) was built on x_r, the old version of your change r′; not bringing it in"],
                "dim": ["xr", "b"],
                "verdict": "CloneX recognises staleness through the change-id (r and r′ are one change), so it doesn't create ρ(b) or offer a merge. Without a change-id (a plain-Git amend), bringing b in would give an add/add conflict on the test file: loud, not silent.",
            },
        ],
        "conclusion": "staleness is detected when a brought-in commit's rep would sit on a composition commit that a newer version of the same change has superseded.",
    },
    {
        "id": "S3",
        "title": "Bob renames a function in dotsync while Ada uses it from the umbrella",
        "repos": [TR, UM, DS],
        "compositions": ["UM"],
        "setup": "dotsync is at d4. At 09:30 Ada starts on the umbrella and adds config loading to trunc and dotsync; her dotsync code calls <code>load_scopes</code>. At 10:00 Bob, working in dotsync alone on bob-mac, renames <code>load_scopes</code> to <code>read_scopes</code> and pushes. Bob never opens the umbrella.",
        "steps": [
            {
                "title": "Start: the umbrella commit U4 is where d4 came in",
                "commits": [("TR", "t4", "t4"), ("UM", "U4", "U4"), ("DS", "d4", "d4")],
                "rep": [("U4", "d4")],
                "is": [("U4", "t4")],
                "text": "U4 is d4's rep. It also <em>is</em> t4; t4's rep is an earlier umbrella commit, not shown.",
            },
            {
                "title": "09:45 Ada commits a1 in the umbrella, touching trunc, dotsync and crates/standards",
                "cmds": ["ada$ git commit -am 'Load config in trunc and dotsync'   → a1"],
                "commits": [("UM", "a1", "a1 (Ada)"), ("TR", "xT", "x_T"), ("DS", "xD", "x_D")],
                "edges": [("U4", "a1"), ("t4", "xT"), ("d4", "xD")],
                "made": [("a1", "xT"), ("a1", "xD")],
                "text": "Mapping a1 down gives x_T (parent t4) and x_D (parent d4, adds <code>src/config.rs</code> calling <code>load_scopes</code>). a1 is the rep of both.",
            },
            {
                "title": "10:00 Bob commits b1 in dotsync and pushes it",
                "cmds": ["bob$ git commit -am 'Rename load_scopes'   → b1, parent d4", "bob$ git push origin main"],
                "commits": [("DS", "b1", "b1 (Bob)")],
                "edges": [("d4", "b1")],
                "text": "This happens on bob-mac and GitHub only. Nothing in the umbrella changes.",
            },
            {
                "title": "10:30 Ada publishes; CloneX tells her dotsync has moved",
                "cmds": [
                    "ada$ cx publish",
                    "trunc:   x_T sent (new PR)",
                    "dotsync: x_D sent (new PR)",
                    "dotsync: b1 (Bob, 'Rename load_scopes') is newer than your base d4 and not in your work",
                ],
                "text": "Publishing copies x_T and x_D to their repos; the DAG doesn't change. The warning is a DAG fact: b1 is a dotsync commit that no commit on Ada's line <em>is</em> or descends from (Q-S3b).",
            },
            {
                "title": "Ada creates b1's rep; it is built on d4's rep, not on her work",
                "cmds": ["ada$ cx fetch dotsync   → ρ(b1): parent U4 (rep of d4), tree = U4's with tools/dotsync := b1"],
                "commits": [("UM", "r_b1", "ρ(b1)")],
                "edges": [("U4", "r_b1")],
                "rep": [("r_b1", "b1")],
                "is": [("r_b1", "t4")],
                "text": "The same object on every machine that brings b1 in (S10).",
            },
            {
                "title": "Ada merges it: an ordinary Git merge in the umbrella",
                "cmds": ["ada$ git merge ρ(b1)   → A2 (clean: Bob changed main.rs, Ada added config.rs)", "ada$ cargo test   → error: cannot find function `load_scopes`"],
                "commits": [("UM", "A2", "A2"), ("DS", "mD", "m_D")],
                "edges": [("a1", "A2"), ("r_b1", "A2"), ("xD", "mD"), ("b1", "mD")],
                "made": [("A2", "mD")],
                "is": [("A2", "xT")],
                "text": "The textual merge is clean, and the break shows up <em>in the umbrella</em>, where Ada can fix it (Q-S3c). Mapping A2 down to dotsync gives m_D = merge(x_D, b1): in dotsync's terms, Ada's branch merged Bob's work. That is what AGENTS.md already asks for (Q-S3d). trunc didn't change, so A2 is still x_T.",
            },
            {
                "title": "Ada fixes the call",
                "cmds": ["ada$ git commit -am 'Use read_scopes'   → a3"],
                "commits": [("UM", "a3", "a3"), ("DS", "fx", "x_fix")],
                "edges": [("A2", "a3"), ("mD", "fx")],
                "made": [("a3", "fx")],
                "is": [("a3", "xT")],
            },
            {
                "title": "Ada publishes again; only dotsync's part changed",
                "cmds": ["ada$ cx publish", "trunc:   unchanged", "dotsync: m_D, x_fix added to your PR"],
                "text": "Ada's dotsync PR branch goes x_D → m_D → x_fix: a fast-forward, adding commits and overwriting nothing (W6). The DAG doesn't change.",
            },
            {
                "title": "Bob merges Ada's dotsync PR on GitHub",
                "cmds": ["github$ merge dotsync PR   → d5 = merge(b1, x_fix)"],
                "commits": [("DS", "d5", "d5")],
                "edges": [("b1", "d5"), ("fx", "d5")],
                "text": "This is the only moment Bob sees Ada's work: an ordinary PR (W1).",
            },
            {
                "title": "Bringing d5 in: its rep's parents are ρ(b1) and a3",
                "cmds": ["ada$ cx fetch dotsync   → ρ(d5): parents ρ(b1), a3"],
                "commits": [("UM", "r_d5", "ρ(d5)")],
                "edges": [("r_b1", "r_d5"), ("a3", "r_d5")],
                "rep": [("r_d5", "d5")],
                "is": [("r_d5", "xT")],
                "verdict": "ρ(b1) is already an ancestor of a3, so the tree outside dotsync is a3's, and dotsync's content is x_fix's, which is d5's. ρ(d5) is a merge with no content change, a child of a3. Ada's line just moves forward to it; no merge is needed.",
            },
        ],
        "conclusion": "concurrent work in a tool comes in as its own rep, beside the umbrella's work, and joins it by an ordinary merge. That merge maps down to the tool's ordinary \"merge main into my branch\" commit, and the break shows up where the author can fix it. Bob sees only Ada's PR.",
    },
    {
        "id": "S6",
        "title": "Two copies of tdd-ratchet, one CVE fix",
        "repos": [UM, ("TK", "tdd-ratchet repo")],
        "compositions": ["UM"],
        "setup": "The umbrella has tdd-ratchet at <code>tools/tdd-ratchet/</code>, at k7. Max adds a frozen copy at v1.1.6 (k6) as <code>fixtures/tdd-ratchet-1.1.6/</code>, for the ledger compatibility tests. Later a CVE needs fixing in both. Each copy is an <em>occurrence</em>, and every tool commit gets one rep per occurrence.",
        "steps": [
            {
                "title": "Start: one occurrence, at tools/",
                "commits": [("TK", "k5", "k5"), ("TK", "k6", "k6 = v1.1.6"), ("TK", "k7", "k7"), ("UM", "R5", "ρ(k5)"), ("UM", "R6", "ρ(k6)"), ("UM", "U5", "U5 = ρ(k7)")],
                "edges": [("k5", "k6"), ("k6", "k7"), ("R5", "R6"), ("R6", "U5")],
                "rep": [("R5", "k5", "tools"), ("R6", "k6", "tools"), ("U5", "k7", "tools")],
                "text": "Each tdd-ratchet commit has its rep at tools/. k5 stands for all of tdd-ratchet's history before v1.1.6.",
            },
            {
                "title": "Max adds the fixture: reps of its history, at fixtures/, built on U5",
                "cmds": ["max$ cx add fixtures/tdd-ratchet-1.1.6 --from tdd-ratchet@v1.1.6   → ρf(k5), ρf(k6)"],
                "commits": [("UM", "f5", "ρf(k5)"), ("UM", "f6", "ρf(k6)")],
                "edges": [("U5", "f5"), ("f5", "f6")],
                "rep": [("f5", "k5", "fixtures"), ("f6", "k6", "fixtures")],
                "is": [("f5", "k7", "tools"), ("f6", "k7", "tools")],
                "text": "The same rule as converting a submodule (S15): history before the occurrence existed gets reps built on the commit it is added to. Each is U5's tree plus the fixture at that commit. U5 is an ancestor of ρf(k6), so Max's line just moves forward to ρf(k6): no merge. <code>git blame fixtures/tdd-ratchet-1.1.6/src/ledger.rs</code> names the real authors (W8). Cost: one umbrella commit per tdd-ratchet commit up to v1.1.6. \"Syncing never moves it\" (Q-S6b) is about which label the fixture follows, so it is level 2.",
            },
            {
                "title": "Max fixes the CVE in both copies in one umbrella commit c",
                "cmds": ["max$ git commit -am 'Reject oversized ledger entries (CVE-2026-1234)'   → c"],
                "commits": [("UM", "c", "c"), ("TK", "xm", "x_main"), ("TK", "xb", "x_bp")],
                "edges": [("f6", "c"), ("k7", "xm"), ("k6", "xb")],
                "made": [("c", "xm", "tools"), ("c", "xb", "fixtures")],
                "text": "Mapping c down at tools/ gives x_main (parent k7); at fixtures/ it gives x_bp (parent k6). They are two different tdd-ratchet commits, with the same message, author and date, so recognisably the same fix (Q-S6c). c is the rep of both, as the owner's model says.",
            },
            {
                "title": "Max publishes: one PR on the current line, one backport on v1.1.6",
                "cmds": ["max$ cx publish", "tdd-ratchet: x_main sent (new PR)", "tdd-ratchet: x_bp sent (new branch on v1.1.6)"],
                "text": "The DAG doesn't change. Which branch names they get is level 2.",
            },
            {
                "title": "tdd-ratchet merges x_main (k8) and tags x_bp as v1.1.7",
                "cmds": ["github$ merge PR   → k8 = merge(k7, x_main)", "max$ git tag v1.1.7 x_bp && git push --tags   (a label; no new commit)"],
                "commits": [("TK", "k8", "k8")],
                "edges": [("k7", "k8"), ("xm", "k8")],
            },
            {
                "title": "Bringing k8 in at tools/: its rep contains the fixture's fix too",
                "cmds": ["max$ cx fetch tdd-ratchet   → ρ(k8) at tools/: parents U5 (rep of k7), c (rep of x_main)"],
                "commits": [("UM", "r_k8", "ρ(k8)")],
                "edges": [("U5", "r_k8"), ("c", "r_k8")],
                "rep": [("r_k8", "k8", "tools")],
                "is": [("r_k8", "xb", "fixtures")],
                "verdict": "Outside tools/, ρ(k8)'s tree is Git's merge of U5 and c, which is c's, so it <em>is</em> x_bp at fixtures/. That is consistent: the fix is in both copies. v1.1.7 needs nothing brought in; x_bp's rep is already c.",
            },
        ],
        "conclusion": "a tool at two paths is two occurrences; reps are per tool commit <em>per occurrence</em>. One umbrella commit can be the rep of two commits of the same tool, one per occurrence. Adding an occurrence builds reps for its history on the commit it is added to, like conversion. Rename and copy detection don't pair the two copies, because neither path is deleted.",
    },
    {
        "id": "S7",
        "title": "tb's history is rewritten (the ledger repair)",
        "repos": [UM, ("TBR", "tb repo")],
        "compositions": ["UM"],
        "setup": "tb's e2 edited the ledger badly. With Max's approval, tb's history from e2 on is rebuilt as e2′, e3′: the same trees except the ledger. The old tip is tagged <code>backup/tb-main-2026-09-09</code>, and tb's main is force-pushed. The umbrella must not rewrite.",
        "steps": S7_STEPS,
        "conclusion": "a rewrite comes in as new reps beside the old ones, joined by one merge. That merge records which tool commit replaces which, and uses the replaced commit as the base, so there are no spurious conflicts and no resurrection of the old history. The umbrella's history is never rewritten.",
    },
    {
        "id": "S7a",
        "title": "Ada had tb work in flight during the rewrite",
        "repos": [UM, ("TBR", "tb repo")],
        "compositions": ["UM"],
        "setup": "S7 again, but before the rewrite Ada committed w on U6, changing <code>tools/tb/src/pane.rs</code>, and published it as a PR in tb (x_w, parent e3). The PR hasn't merged when tb is rewritten.",
        "steps": S7_STEPS[:1] + [
            {
                "title": "Before the rewrite, Ada commits w in the umbrella and publishes x_w",
                "cmds": ["ada$ git commit -am 'Handle closed panes'   → w", "ada$ cx publish   → tb: x_w sent (new PR)"],
                "commits": [("UM", "w", "w (Ada)"), ("TBR", "xw", "x_w")],
                "edges": [("U6", "w"), ("e3", "xw")],
                "made": [("w", "xw")],
            },
        ] + S7_STEPS[1:] + [
            {
                "title": "Ada merges M into her line; her tb change is rebuilt on e3′",
                "cmds": ["ada$ git merge M   → A (tools/tb: e3 → e3′ from M, plus w's pane.rs change: clean)"],
                "commits": [("UM", "A", "A"), ("TBR", "xw2", "x_w′")],
                "edges": [("w", "A"), ("M", "A"), ("e3b", "xw2")],
                "made": [("A", "xw2")],
                "dim": ["xw"],
                "text": "Here the ordinary merge is right: its base is U6, whose tools/tb is e3, so it applies w's change on top of e3′. Mapping A down <em>with M's Supersedes trailer</em> treats x_w as built on a replaced commit, and regenerates it on the replacement: x_w′, parent e3′, with w's message and author. That is what jj does to the descendants of a rewritten commit.",
                "verdict": "Republishing updates Ada's own PR branch from x_w to x_w′, replacing only her own commit, as anyone must after an upstream force-push. The alternative mapping, merge(x_w, e3′), would carry e2 and e3 back into tb through her PR.",
            },
        ],
        "conclusion": "(candidate rule) a tool commit built on a superseded commit is regenerated on its replacement when mapped through a merge carrying the Supersedes record. This needs its own attack before it is trusted: who may write a Supersedes trailer, and what if it is wrong (the forged-claim story).",
    },
]
